
NAME = thread_pool

CC = g++
CPPFLAGS = -I .
CFLAGS = -ansi -pedantic-errors -Wall -Wextra -g -D_DEBUG

SOURCE = thread_pool.cpp thread_pool_test.cpp
OBJS = thread_pool.o thread_pool_test.o

.PHONY: all
all: 

: 
	   -o a.out

: 
	  -c 

